server:
  port: 8080
mpesa:
  daraja:
    consumer-key: kAg5pZcWJVfuFihVaSIXNwN170IeBIYY
    consumer-secret: ELLQw8YWcnvnwYVj
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    shortCode: 133857
    responseType: Completed
    confirmation-url: https://705f-102-68-76-227.ngrok.io/mobile-money/confirmation
    validation-url: https://705f-102-68-76-227.ngrok.io/mobile-money/validation
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://adf94cda8cd2.ngrok.io/mobile-money/b2c-transaction-result
    b2c-queue-timeout-url: https://adf94cda8cd2.ngrok.io/mobile-money/b2c-queue-timeout
    b2c-initiator-name: apiop37
    b2c-initiator-password: Safaricom3021#
    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    stkPushShortCode: 174379
    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkPushRequestCallbackUrl: https://0b60-197-237-157-233.ngrok.io/mobile-money/stk-transaction-result